# recipe
# target: ingredients
#	instructions
newecho: newecho.c
	gcc -o newecho newecho.c

newcat: newcat.c
	gcc -o newcat newcat.c

all: newecho.c newcat.c
	gcc -o newecho newecho.c
	gcc -o newcat newcat.c

clean:
	rm -f newecho newcat
